### ISSUE TITLE
Apply pluginPrefix to scoped packages

### ISSUE THREAD

**Issue by shinnn** [unifiedjs/unified-engine#30]
### Current behavior

When I have installed `@shinnn/remark-preset-lint` package to the current project directory, add

```json
"remarkConfig": {
  "plugins": [
    "@shinnn/preset-lint"
  ]
}
```

to `package.json` and run the code below:

```js
'use strict';

const engine = require('unified-engine')
var remark = require('remark')

engine({
  processor: remark,
  files: [__filename],
  pluginPrefix: 'remark',
  packageField: 'remarkConfig'
}, () => {});
```

it prints this error:

```console
$ node index.js .
index.js
  1:1  error  Error: Could not find module `@shinnn/preset-lint`
    at addModule (/Users/shinnn/github/remark/node_modules/unified-engine/lib/configuration.js:242:27)
    at use (/Users/shinnn/github/remark/node_modules/unified-engine/lib/configuration.js:203:7)
    at addEach (/Users/shinnn/github/remark/node_modules/unified-engine/lib/configuration.js:188:9)
    at addPreset (/Users/shinnn/github/remark/node_modules/unified-engine/lib/configuration.js:164:9)
    at merge (/Users/shinnn/github/remark/node_modules/unified-engine/lib/configuration.js:150:5)
    at Config.create (/Users/shinnn/github/remark/node_modules/unified-engine/lib/configuration.js:105:5)
    at done (/Users/shinnn/github/remark/node_modules/unified-engine/lib/find-up.js:148:20)
```

As you can see, [`pluginPrefix` option](https://github.com/unifiedjs/unified-engine/blob/1b5842ced969d218e971b0d4fb40a255b4e7d643/doc/options.md#optionspluginprefix) doesn't automatically prefix [scoped packages](https://docs.npmjs.com/misc/scope).

### Expected behavior

I'd like `@${scope}/{plugin name without pluginPrefix}` to be resolved to `@${scope}/{full plugin name}`.

-------

@wooorm if this proposal is acceptable to you, I can create a pull request.

**Comment by wooorm** [comment]
This should go in [`load-plugin`](https://www.npmjs.com/package/load-plugin) I believe?

I’m a bit worried slowing stuff down by adding another case though. So I hope you can find a solution that works fast! Other than that i’m :+1:

**Comment by wooorm** [comment]
@shinnn Ping!

**Comment by wooorm** [comment]
Released!
